### ISSUE TITLE
Doesn't reload LESS files with ember 1.12.0-beta.1+canary and ember-cli 0.2.1

### ISSUE THREAD

**Issue by melnychuk** [xomaczar/ember-cli-styles-reloader#1]
The addon doesn't seem to work for me. Page does not react to any changes I'm doing to my *.less files.

Besides, it also seems to build the whole thing:

```
file changed styles\app.less
Note: The code generator has deoptimised the styling of "app/models/item.js" as it exceeds the max of "100KB".
Warning: ignoring input sourcemap for bower_components/route-recognizer/dist/route-recognizer.js because ENOENT, no such file or directory 'C:\Users\olegmel\Documents\delvember\tmp\tree_merger-tmp_dest_dir-0x3sKs5p.tmp\bower_components\route-recognizer\dist\route-recognizer.js.map'

Build successful - 4805ms.

Slowest Trees                                 | Total
----------------------------------------------+---------------------
Babel                                         | 1217ms
LessCompiler                                  | 682ms
Funnel: App JS Files                          | 334ms
Concat: Vendor                                | 315ms

Slowest Trees (cumulative)                    | Total (avg)
----------------------------------------------+---------------------
Babel (5)                                     | 1480ms (296 ms)
LessCompiler (1)                              | 682ms
Funnel: App JS Files (1)                      | 334ms
Concat: Vendor (1)                            | 315ms
```

Am I missing anything?

**Comment by melnychuk** [comment]
They seem to be built and compiled, but not reloaded automatically. When I reload the page manually, it updates nicely.

**Comment by xomaczar** [comment]
Can you provide which OS and browser, also include the version of less compiler you are experiencing this issue on.

**Comment by melnychuk** [comment]
Right, sorry.

I'm on Windows 10 Technical Preview (build 10041)
Using "ember-cli-less" version 1.2.0

**Comment by xomaczar** [comment]
Are u using chrome?

**Comment by melnychuk** [comment]
I've tried in multiple browsers. But yes, Chrome (stable and canary), IE.

**Comment by xomaczar** [comment]
@melnychuk Sorry for taking so long. I am upgraded the styles-reloader, everything seems to work with  IE11, Windows10 & ember-cli 0.2.3
Again my setup is a bit different, I am on ubuntu updating the less styles with live-reloading on windows10, IE11.

Can we maybe get together and try to resolve your issue?

**Comment by melnychuk** [comment]
@xomaczar hey, no worries at all :) I'm all up for trying to figure this out. Will Skype work?

**Comment by xomaczar** [comment]
@melnychuk yeah lets do it. I am available tonight

**Comment by melnychuk** [comment]
Hehe... Define "tonight" ;) GMT+1 here (Oslo). Feel free to add me, I'm melnychuk.oleg on Skype.

**Comment by xomaczar** [comment]
@melnychuk can you try a new version which was release today. I made some changes where only targeted resources get reloaded i.e. app-name.css/vendor.css vs. *.css. Let me know if that fixes windows issue

**Comment by xomaczar** [comment]
@melnychuk can you try a new version which was released today. I made some changes where only targeted resources get reloaded i.e. app-name.css/vendor.css vs. *.css. Let me know if that fixes windows issue

**Comment by xomaczar** [comment]
Haven't heard from you in a while, I am going to close this issue for now. I am willing to reopen, if this specific issue still exists.

**Comment by buschtoens** [comment]
I'm having the same / a similar problem Among other addons I use:
- ember-cli-styles-reloader
- ember-cli-sass
- ember-component-css

When I edit a component style file, I can see in the Chrome Dev Tools, that the stylesheet gets "reloaded" (DOM action), however, the new stylesheet is not applied.

This happens because only the vendor stylesheet query parameter gets changed. The app stylesheet query parameter stays the same, until I reload or save the main `app.sass`.

**Comment by buschtoens** [comment]
The [reload logic](https://github.com/xomaczar/ember-cli-styles-reloader/blob/master/lib/styles-reloader.js#L37-39) is "flawed". It assumes that styles files are only located inside the `styles` directory.

This is not true for ember-component-css. Maybe we should just reload both files, whenever a file that matches the correct file type suffix changes? Or we'd have to add the `components` path as well.
