### ISSUE TITLE
Installing it kills all reloading

### ISSUE THREAD

**Issue by mastastealth** [xomaczar/ember-cli-styles-reloader#10]
I have also installed the autoprefixer and sass addons, for what it's worth.

After installing the styles-reloader, updating my scss does nothing to the page. I see the update in the CLI, but Firefox never gets a reload and nothing shows up in the console there either. This is on Windows 7. A manual refresh does show the changes.

**Comment by xomaczar** [comment]
Have you tried with a different browser, chrome preferably. What are the sass addons you're referring to? Does your normal js/hbs livereload work? Does the styles-reloader works on a blank ember-cli project with your dev environment? Let me know what you find it...

**Comment by mastastealth** [comment]
- Chrome, Opera and Firefox all fail
- ember-cli-autoprefixed and ember-cli-sass
-  Nope, kills _all_ reloading, including normal js/hbs reloads
- I've tried 2 clean projects that are reloading fine, but once the livereload addon is added, stop reloading

**Comment by xomaczar** [comment]
Can we get together and screen share? Which timezone are you in?

**Comment by mastastealth** [comment]
Brand new project:
![works](https://cloud.githubusercontent.com/assets/1221228/9173709/d36f8248-3f49-11e5-948e-62a34861f1be.gif)
Only install styles-reloader:
![notworks](https://cloud.githubusercontent.com/assets/1221228/9173710/d382559e-3f49-11e5-889f-5f1d3c51d25d.gif)

It did reload upon editing the hbs this time, but something is clearly weird here. I am on EST, feel free to add me on Skype (same username as here) and we can organize something through there. :+1:

**Comment by buschtoens** [comment]
If I may chip in here for a bit. I suspect that this only fails on Windows. And I do believe I know why.

[This regex part](https://github.com/xomaczar/ember-cli-styles-reloader/blob/master/lib/styles-reloader.js#L20) starts with a `/` forward slash. However, Windows paths use `\` backwards slashes. Which is why [`shouldReload(filePath)`](https://github.com/xomaczar/ember-cli-styles-reloader/blob/master/lib/styles-reloader.js#L34) always returns `false`.

I hope to have saved you guys a lot of trouble. :D
Windows sucks. Especially with ember-cli IMHO.

**Comment by buschtoens** [comment]
@mastastealth I highly recommend setting up a Linux VM for development. I use Windows 10 as my main OS, however, all development is done in a Linux VM. It spares you so many headaches. ember-cli also runs **a lot** faster on Linux.

I start the VM headless without a GUI, connect to it via SSH and mount a SMB share via the internal network bridge. This way I can edit all files with my Windows editor of choice.

**Comment by mastastealth** [comment]
@buschtoens I do have one (had to do it for Ruby stuff, which also seems to hate Windows), as well as Mac machines, but I do like to help where possible to enhance things for Windows devs out there, even if by a little bit. ;P

**Comment by buschtoens** [comment]
Yeah, if Windows only had a shell on par with bash.

Anyhow, that's just my opinion. But do try it. The performance difference is insane. And I doubt that the ember-cli team will ever get it to run as smoothly on Windows as they do on Linux. I suspect that demand is little as well. AFAIK most devs use OS X or Linux for ember-cli.

**Comment by xomaczar** [comment]
@mastastealth I believe @buschtoens is correct. Can you please verify that substituting [this regex](https://github.com/xomaczar/ember-cli-styles-reloader/blob/master/lib/styles-reloader.js#L20) for

``` javascript
  var appStylePath = path.join(options.project.root, 'app', 'styles', '*');
```

fixes your issue.

**Comment by xomaczar** [comment]
@mastastealth does the latest release (v0.1.8) fixes your issue on Windows?
