### ISSUE TITLE
Fails with ember-cli 1.13.11

### ISSUE THREAD

**Issue by swastik** [xomaczar/ember-cli-styles-reloader#14]
I just upgraded to ember-cli 1.13.11 and this fails to reload the styles after there's a change to the files. It picks up the change just fine, and it reloads, however it seems here:

```
var liveReloadHostname = [
  (options.ssl ? 'https://' :'http://'),
  (options.liveReloadHost || options.host),
  ':',
  options.liveReloadPort
].join('');
```

`options.liveReloadHost` is now undefined and so is `options.host`. Thus, it constructs the wrong URL and hence sends the request to the wrong URL.

An easy fix to this is to just add a localhost fallback since this is most likely to be used only in dev:

```
(options.liveReloadHost || options.host || "localhost")
```

... but I'm not sure if it's right to do it here. Should I open an issue on ember-cli's repository?

**Comment by xtian** [comment]
I'm having this issue as well

**Comment by xomaczar** [comment]
If someone has any time we need to investigate if it's ember-cli issue (...I know it's ember-cli issue, I am just unsure if I was using private api therefore no guarantees). Fallback to localhost is fine (as a stop-gap), however there are users out there that use VM to dev and test changes on host.

**Comment by xomaczar** [comment]
@swastik I just verified and you are absolutely right. In ember-cli@~1.13.11/12 if liveReloadHost was not set, it's undefined.
Until I push the fix (I've got other fixes like supporting addon development, podded styles, etc) you guys can edit your .ember-cli config file and include liveReloadHost like so.

``` js
{
 liveReloadHost: '127.0.0.1' //or localhost whatever hostname/ip you are using in browser's address bar
}
```

Let me know if that fixes your issue and thanks for reporting the bug.

**Comment by swastik** [comment]
Thank you! That works pretty well! :smile: 

Should I close this issue?

**Comment by xomaczar** [comment]
Not yet. I'd like to add this to README.md. Would you be willing to author this PR?

**Comment by swastik** [comment]
Sure! I'll send a PR. Do you want me to include just the warning and the solution?

**Comment by swastik** [comment]
Okay, sent a PR! Let me know if you need any changes! 😀

**Comment by blimmer** [comment]
@xomaczar what do you think about pushing a release for this before the other features?

 because of issues like #12 , I thought that the problem wasn't solved.

**Comment by yadomi** [comment]
+1 for the release. 

Currently this plugin is broken on every `ember-cli` app running  > `1.13.x`, kinda useless without fix.
